### ISSUE TITLE
ACTIVIDAD 5 CUADRO COMPARATIVO DE LOS TIPOS DE TEXTOS YAEL TRINIDAD

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-YaelTrinidad#1]
[CUADRO COMP T DE TEXTOS YAEL T.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-YaelTrinidad/files/9620207/CUADRO.COMP.T.DE.TEXTOS.YAEL.T.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De la actividad 5
Obtuviste un 16.8% de los 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
